---
apiVersion: build.rhone.io/v2
contributors:
  - email: nikolaj@majorov.biz
    name: Nikolaj Majorov
description: simple rest service in python
interpreter-version: '3'
language: python
name: python-server-simple
version: 3-Alpha
env:
  - TEST_SEVER_HOST = "{{rhone_server_hostname}}"
  - TEST_SERVER_IP = "{{ rhone_server_ip }}"

build_podman_params:
  - --add-host "{{ rhone_server_hostname }}:{{rhone_server_ip}}"
  - -e  KEYCLOAK_URL="{{ rhone_server_hostname }}:8080"
